CREATE TABLE ROLES (
  ID_ROLE INT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_ROLE),
  CONSTRAINT ID_ROLE_UNIQUE UNIQUE  (ID_ROLE),
  CONSTRAINT NAME_UNIQUE UNIQUE  (NAME)
) ;

CREATE TABLE USERS (
  ID_USER INT NOT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  ID_ROLE INT NOT NULL DEFAULT 1,
  PASSWORD VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_USER),
  CONSTRAINT ID_USER_UNIQUE UNIQUE  (ID_USER),
  CONSTRAINT EMAIL_UNIQUE UNIQUE  (EMAIL)
 ,
  CONSTRAINT FK_USER_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLES (ID_ROLE) ON DELETE NO ACTION ON UPDATE NO ACTION
) ;

CREATE INDEX FK_USER_ROLE_IDX ON USERS (ID_ROLE);

CREATE TABLE TWEETS (
  ID_TWEET INT NOT NULL,
  EXTERNAL_ID VARCHAR(20) NOT NULL,
  TEXT VARCHAR(255) DEFAULT NULL,
  UNMODIFIED_TEXT VARCHAR(255) DEFAULT NULL,
  SOURCE VARCHAR(255) DEFAULT NULL,
  CREATE_AT VARCHAR(20) NOT NULL,
  FROM_USER VARCHAR(255) NOT NULL,
  PROFILE_IMAGE_URL VARCHAR(255) NOT NULL,
  TO_USER_ID VARCHAR(20) NOT NULL DEFAULT '0',
  FROM_USER_ID VARCHAR(20) NOT NULL DEFAULT '0',
  IN_REPLY_TO_STATUS_ID VARCHAR(20) DEFAULT NULL,
  LANGUAGE_CODE VARCHAR(255) NOT NULL,
  RETWEETED_COUNT INT NOT NULL DEFAULT 0,
  RETWEETED INT NOT NULL DEFAULT 0,
  RETWEETED_STATUS VARCHAR(255) DEFAULT NULL,
  RETWEET INT NOT NULL DEFAULT 0,
  FAVORITED INT NOT NULL DEFAULT 0,
  FAVORITE_COUNT INT NOT NULL DEFAULT 0,
  IN_REPLY_TO_USER_ID VARCHAR(20) DEFAULT NULL,
  IN_REPLY_TO_SCREEN_NAME VARCHAR(255) DEFAULT NULL,
  TWEETER_USER_ID INT NOT NULL,
  PRIMARY KEY (ID_TWEET)
 ,
  CONSTRAINT FK_TWEET_TWITTER_USER FOREIGN KEY (TWEETER_USER_ID) REFERENCES TWITTER_USERS (ID_TWITTER_USER) ON DELETE NO ACTION ON UPDATE NO ACTION
) ;

CREATE INDEX FK_TWEET_TWITTER_USER_IDX ON TWEETS (TWEETER_USER_ID);

CREATE TABLE TWITTER_USERS (
  ID_TWITTER_USER int NOT NULL,
  EXTERNAL_ID varchar(20) NOT NULL,
  SCREEN_NAME varchar(255) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  URL varchar(255) DEFAULT NULL,
  PROFILE_IMAGE_URL varchar(255) NOT NULL,
  DESCRIPTION varchar(255) DEFAULT NULL,
  LOCATION varchar(255) DEFAULT NULL,
  LANGUAGE varchar(255) NOT NULL,
  TIME_ZONE varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID_TWITTER_USER)
) ;