INSERT INTO USERS (ID_USER, USERNAME, PASSWORD, ID_ROLE, EMAIL) VALUES ('1', 'INGCAG', 'ingcag123456', '1', 'INGCAG@EMAIL.COM');
INSERT INTO USERS (ID_USER, USERNAME, PASSWORD, ID_ROLE, EMAIL) VALUES ('2', 'VALINAYO', 'admin123', '1', 'VLINAYO@CORREO.COM');
INSERT INTO USERS (ID_USER, USERNAME, PASSWORD, ID_ROLE, EMAIL) VALUES ('3', 'OTRO', 'otra123', '2', 'CORREO@NOTIENE.COM');