CREATE TABLE `ROLES` (
  `ID_ROLE` INT(10) NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_ROLE`),
  UNIQUE KEY `ID_ROLE_UNIQUE` (`ID_ROLE`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `USERS` (
  `ID_USER` INT(10) NOT NULL,
  `EMAIL` VARCHAR(255) DEFAULT NULL,
  `ID_ROLE` INT(10) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `USERNAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_USER`),
  UNIQUE KEY `ID_USER_UNIQUE` (`ID_USER`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`),
  KEY `FK_USER_ROLE_IDX` (`ID_ROLE`),
  CONSTRAINT `FK_USER_ROLE` FOREIGN KEY (`ID_ROLE`) REFERENCES `ROLES` (`ID_ROLE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
