CREATE TABLE `ROLES` (
  `ID_ROLE` INT(10) NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_ROLE`),
  UNIQUE KEY `ID_ROLE_UNIQUE` (`ID_ROLE`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `USERS` (
  `ID_USER` INT(10) NOT NULL,
  `EMAIL` VARCHAR(255) DEFAULT NULL,
  `ID_ROLE` INT(10) NOT NULL DEFAULT 1,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `USERNAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_USER`),
  UNIQUE KEY `ID_USER_UNIQUE` (`ID_USER`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`),
  KEY `FK_USER_ROLE_IDX` (`ID_ROLE`),
  CONSTRAINT `FK_USER_ROLE` FOREIGN KEY (`ID_ROLE`) REFERENCES `ROLES` (`ID_ROLE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TWEETS` (
  `ID_TWEET` INT(10) NOT NULL,
  `EXTERNAL_ID` INT(50) NOT NULL,
  `TEXT` VARCHAR(255) DEFAULT NULL,
  `UNMODIFIED_TEXT` VARCHAR(255) DEFAULT NULL,
  `SOURCE` VARCHAR(255) DEFAULT NULL,
  `TWEETER_USER_ID` INT(50) NOT NULL,
  `CREATE_AT` INT(20) NOT NULL,
  `FROM_USER` VARCHAR(255) NOT NULL,
  `PROFILE_IMAGE_URL` VARCHAR(255) NOT NULL,
  `TO_USER_ID` INT(50) NOT NULL DEFAULT 0,
  `FROM_USER_ID` INT(50) NOT NULL,
  `IN_REPLY_TO_STATUS_ID` INT(50) DEFAULT NULL,
  `LANGUAGE_CODE` VARCHAR(255) NOT NULL,
  `RETWEETED_COUNT` INT(10) NOT NULL DEFAULT 0,
  `RETWEETED` INT(1) NOT NULL DEFAULT 0,
  `RETWEETED_STATUS` VARCHAR(255) DEFAULT NULL,
  `RETWEET` INT(1) NOT NULL DEFAULT 0,
  `FAVORITED` INT(1) NOT NULL DEFAULT 0,
  `FAVORITE_COUNT` INT(10) NOT NULL DEFAULT 0,
  `IN_REPLY_TO_USER_ID` INT(50) DEFAULT NULL,
  `IN_REPLY_TO_SCREEN_NAME` VARCHAR(255) DEFAULT NULL,
   PRIMARY KEY (`ID_TWEET`)
 ) ENGINE=InnoDB DEFAULT CHARSET=latin1;