package com.example.spring.mysql.controller;

import com.example.spring.mysql.model.MyModel;
import com.example.spring.mysql.model.User;
import com.example.spring.mysql.repository.UsersRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@RestController
@RequestMapping(path = "/mySQL")
public class MyController {

    @Autowired
    private MyModel model;

    @RequestMapping(value = "/sayHello", method = RequestMethod.GET)
    public String sayHello() {
        model = new MyModel("Hello World!");
        return model.toString();
    }

    /*
    readUser	-> GET		-> {idUser}			-> <User>
    createUser	-> POST	-> users/		-> <User>
    editUser	-> PUT		-> {id, <User>}	-> <User>
    listUsers	-> GET		-> users/		-> list(<User>)
    */

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UsersRepository userRepository;
/*
    @RequestMapping(value="/{idUser}", method = RequestMethod.GET)
    public User (String idUser){
        userRepository = new UserRepository(idUser);
        return model.toString();
    }
    */

    /*
    @GetMapping(path = "/createUser") // Map ONLY GET Requests
    public @ResponseBody
    String createUser(@RequestParam String userName, @RequestParam String password, @RequestParam String email, @RequestParam String idRole) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Integer role = Integer.getInteger(idRole);
        User u = new User(userName, password, email, role);
        userRepository.save(u);
        return "Saved";
    }
    */

    @GetMapping(path="/listUsers")
    public @ResponseBody Iterable<User> listUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/readUser")
    public @ResponseBody
    Optional<User> readUser(@RequestParam String id){
        Long userId = Long.valueOf(id.toString());
        return userRepository.findById(userId);
    }
}
